spring:
    jpa:
      hibernate:
        ddl-auto: update
        generate-ddl: false

      properties:
        format_sql: true
        hibernate:
          show-sql: true
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
      hiddenmethod:
        filter:
          enabled: true

    mustache:
      suffix: .html

    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

level:
  org.hibernate.SQL: trace
  org.hibernate.type: trace