name: spring boot server CI/CD

on:
  push:
    branches: [ main ]

env:
  S3_BUCKET_NAME: rental-deploy
  
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build -x test
      
    # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy
        
    # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy
      
    # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp appspec.yml ./deploy

    # script files 복사
    - name: Copy script
      run: cp ./scripts/*.sh ./deploy

    - name: Make zip file
      run: zip -r ./rentalmarket.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Download application.properties from S3
      run: aws s3 cp s3://$S3_BUCKET_NAME/application.properties ./
      
    # 다운로드한 application.properties 파일을 resources 디렉토리로 이동
    - name: Move application.properties to resources
      run: mv application.properties ./src/main/resources/
      
    - name: Upload to S3
      run:  aws s3 cp --region ap-northeast-2 ./rentalmarket.zip s3://$S3_BUCKET_NAME/
      

    # Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
          --application-name rentalmarket \
          --deployment-group-name rental-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=rental-deploy,bundleType=zip,key=rentalmarket.zip \
          --region ap-northeast-2
