name: spring boot server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RESOURCE_PATH: ./src/main/resources/application.yml
  cloud.aws.region.static: ap-northeast-2
  cloud.aws.region.stack.auto: false
  spring.datasource.url: com.mysql.cj.jdbc.Driver

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        cloud.aws.credentials.access-key: ${{ secrets.AWS_S3_ACCESS_KEY }}
        cloud.aws.credentials.secret-key: ${{ secrets.AWS_S3_SECRET_KEY }}
        cloud.aws.s3.bucket: ${{ secrets.AWS_S3_BUCKET }}
        
  
    - name: Generate Environment Variables File for Properties
      with:
        files: ${{ env.RESOURCE_PATH }}
        spring.datasource.url: ${{ secrets.DB_URL }}
        spring.datasource.username: ${{ secrets.DB_USERNAME }}
        spring.datasource.password: ${{ secrets.DB_PW }}
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
