name: spring boot server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RESOURCE_PATH: ./src/main/resources/application.yml
  cloud.aws.s3.bucket: rentalbuckettest1
  cloud.aws.region.stack.auto: false

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Configure AWS credentials		#aws credentials 생성
      uses: aws-actions/configure-aws-credentials@v1
      with:
        cloud.aws.credentials.access-key: ${{ secrets.AWS_ACCESS_KEY }}	#secrets 변수 사용
        cloud.aws.credentials.secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        cloud.aws.region.static: ${{ secrets.AWS_REGION }}
        
      # s3 업로드
    - name: upload build directory to s3
      run: aws s3 cp dist/ s3://your_bucket --recursive  #s3 bucket에 업로드


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
